minimum_pre_commit_version: 3.6.0
repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.1.8"
    hooks:
      - id: ruff
      
  - repo: https://github.com/psf/black
    rev: "23.12.0"
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.1
    hooks:
      - id: mypy
